name: Github Actions CI-CD
on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: CI-pre_build # ${{ secrets.AWS_ACCOUNT_ID }}
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions"
        IMAGE_TAG=$(TZ=${{ secrets.TZ }} date +"%Y-%m-%d.%H.%M.%S")
        aws ecr get-login-password --region ${{ secrets.AWS_DEFAULT_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_DEFAULT_REGION }}.amazonaws.com 
    
    - name: CI-build
      run: |
        docker build -t ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_DEFAULT_REGION }}.amazonaws.com/${{ secrets.IMAGE_REPO_NAME}}:${{ secrets.IMAGE_TAG}} .
    
    - name: CI-post_build
      run: |
        docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_DEFAULT_REGION }}.amazonaws.com/${{ secrets.IMAGE_REPO_NAME}}:${{ secrets.IMAGE_TAG}}

    - name: CD-full
      run: | 
        git clone origin https://WhAnci:${{ secrets.ghub_token }}@github.com/WhAnci/gac-gitops.git
        sed -i "s|586639730662.dkr.ecr.ap-northeast-2.amazonaws.com/[^ ]*|586639730662.dkr.ecr.ap-northeast-2.amazonaws.com/${{ secrets.IMAGE_REPO_NAME}}:${{ secrets.IMAGE_TAG}}|g" gac-gitops/deploy.yaml
        cd gac-gitops
        git add deploy.yaml
        git commit -m "Update deployment image to ${{ secrets.IMAGE_TAG}}"
        git push origin https://WhAnci:${{ secrets.ghub_token }}@github.com/WhAnci/gac-gitops.git
