name: Github Actions CI-CD
on:
  push:
    branches: [ main ]

  workflow_dispatch:

env:
  IMAGE_TAG: $(TZ='KST-9' date +"%Y-%m-%d.%H.%M.%S")

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
      with:
        AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

    - name: CI-pre_build # 
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions"
        aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin 586639730662.dkr.ecr.ap-northeast-2.amazonaws.com 
    
    - name: CI-build
  
      run: |
        docker build -t 586639730662.dkr.ecr.ap-northeast-2.amazonaws.com/gac-app:"$IMAGE_TAG" .
    
    - name: CI-post_build
      run: |
        docker push 586639730662.dkr.ecr.ap-northeast-2.amazonaws.com/gac-app:"$IMAGE_TAG"

    - name: CD-full
      run: | 
        git clone origin https://WhAnci:${{ secrets.ghub_token }}@github.com/WhAnci/gac-gitops.git
        sed -i "s|586639730662.dkr.ecr.ap-northeast-2.amazonaws.com/[^ ]*|586639730662.dkr.ecr.ap-northeast-2.amazonaws.com/gac-app:"$IMAGE_TAG"|g" gac-gitops/deploy.yaml
        cd gac-gitops
        git add deploy.yaml
        git commit -m "Update deployment image to "$IMAGE_TAG""
        git push origin https://WhAnci:${{ secrets.ghub_token }}@github.com/WhAnci/gac-gitops.git
