name: Github Actions CI-CD
on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    

    steps:
    - uses: de-vri-es/setup-git-credentials@v2
      with:
        credentials: ${{secrets.PAT}}
    - uses: actions/checkout@v4
    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y-%m-%d-%H-%M-%S')" >> "$GITHUB_OUTPUT"
    - run: echo ${{ steps.date.outputs.date }}
      
    - name: CI-pre_build # 
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions"
        
        aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin 586639730662.dkr.ecr.ap-northeast-2.amazonaws.com 
    
    - name: CI-build
  
      run: |
        docker build -t 586639730662.dkr.ecr.ap-northeast-2.amazonaws.com/gac-app:${{ steps.date.outputs.date }} .
    
    - name: CI-post_build
      run: |
        docker push 586639730662.dkr.ecr.ap-northeast-2.amazonaws.com/gac-app:${{ steps.date.outputs.date }}
    - name: CD-full
      run: | 
        git remote add origin https://github.com/whanci/gac-gitops.git
        cd gac-gitops
        sed -i "s|586639730662.dkr.ecr.ap-northeast-2.amazonaws.com/[^ ]*|586639730662.dkr.ecr.ap-northeast-2.amazonaws.com/gac-app:${{ steps.date.outputs.date }}|g" deploy.yaml
        git add .
        git commit -m "Update deployment image to ${{ steps.date.outputs.date }}"
        git push -u origin main
    
