name: Github Actions CI-CD
on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    

    steps:
    - uses: actions/checkout@v4
    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y-%m-%d-%H-%M-%S')" >> "$GITHUB_OUTPUT"
    - run: echo ${{ steps.date.outputs.date }}
      
    - name: CI-pre_build # 
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions"
        aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin 586639730662.dkr.ecr.ap-northeast-2.amazonaws.com 
    - name: CI-build
  
      run: |
        docker build -t 586639730662.dkr.ecr.ap-northeast-2.amazonaws.com/gac-app:${{ steps.date.outputs.date }} .
    
    - name: CI-post_build
      run: |
        docker push 586639730662.dkr.ecr.ap-northeast-2.amazonaws.com/gac-app:${{ steps.date.outputs.date }}
    - name: checkout
      uses: actions/checkout@v4
      with:
        repository: <my>/<helm-repo>
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: CD
      run: | 
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@github.com"
        git add .
        git commit -m "Update tag in values.yaml" --author "github-actions[bot] <github-actions[bot]@github.com>"
        git push origin main
    
